--!strict
--OwnershipRegistry.lua
--!native
--!optimize 2

--[[
    MIT License
    Copyright (c) 2026 VeDevelopment

    VetraNet/Authority/OwnershipRegistry.lua
    Maps cast ID to owning player on the server.

    Why does this module exist?
    The client submits cast IDs in fire and hit payloads. Without a server-side
    ownership map, a malicious client could include any cast ID in a hit payload,
    potentially claiming hits for bullets fired by other players. The ownership
    registry is the authoritative source: a hit is only processed if the
    submitting player's cast ID resolves to them in this registry.

    Cast IDs are u32 values generated by the server (not the client).
    The server assigns a fresh ID to every successful Fire() call and stores
    the mapping here. When the cast terminates the mapping is removed.

    SERVER-ONLY. Errors at require() time if loaded on the client.
]]

local Identity          = "OwnershipRegistry"

local OwnershipRegistry = {}
OwnershipRegistry.__type = Identity

local OwnershipRegistryMetatable = table.freeze({
	__index = OwnershipRegistry,
})

-- ─── References ──────────────────────────────────────────────────────────────

local Core = script.Parent.Parent.Core

-- ─── Module References ───────────────────────────────────────────────────────

local Authority  = require(Core.Authority)
local LogService = require(Core.Logger)

Authority.AssertServer("OwnershipRegistry")

-- ─── Logger ──────────────────────────────────────────────────────────────────

local Logger = LogService.new(Identity, false)

-- ─── Cached Globals ──────────────────────────────────────────────────────────

local table_clear   = table.clear
local string_format = string.format

-- ─── Factory ─────────────────────────────────────────────────────────────────

function OwnershipRegistry.new(): any
	local self = setmetatable({
		-- [castId: number] → Player
		_CastToPlayer = {},
		-- [Player] → { castId: number }  (set of cast IDs owned by player)
		_PlayerToCasts = setmetatable({}, { __mode = "k" }),
	}, OwnershipRegistryMetatable)
	return self
end

-- ─── API ─────────────────────────────────────────────────────────────────────

-- Register ownership of a cast ID for a player.
-- Called immediately after the server solver fires a new bullet.
function OwnershipRegistry.Register(self: any, CastId: number, Player: Player)
	if self._CastToPlayer[CastId] then
		Logger:Warn(string_format(
			"OwnershipRegistry.Register: castId %d already registered — overwriting",
			CastId
		))
	end
	self._CastToPlayer[CastId] = Player

	local PlayerCasts = self._PlayerToCasts[Player]
	if not PlayerCasts then
		PlayerCasts = {}
		self._PlayerToCasts[Player] = PlayerCasts
	end
	PlayerCasts[CastId] = true
end

-- Release a cast ID mapping when the bullet terminates.
-- Called from Vetra's OnTerminated signal.
function OwnershipRegistry.Unregister(self: any, CastId: number)
	local Owner = self._CastToPlayer[CastId]
	if Owner then
		local PlayerCasts = self._PlayerToCasts[Owner]
		if PlayerCasts then
			PlayerCasts[CastId] = nil
		end
	end
	self._CastToPlayer[CastId] = nil
end

-- Returns the player who owns the given cast ID, or nil if not found.
function OwnershipRegistry.GetOwner(self: any, CastId: number): Player?
	return self._CastToPlayer[CastId]
end

-- Returns true if the given player owns the given cast ID.
-- Used by hit processing to reject cross-player hit spoofs.
function OwnershipRegistry.IsOwner(self: any, CastId: number, Player: Player): boolean
	return self._CastToPlayer[CastId] == Player
end

-- Returns the list of all cast IDs currently owned by the given player.
-- Used during disconnect cleanup to purge all of that player's in-flight bullets.
function OwnershipRegistry.GetCastsForPlayer(self: any, Player: Player): { number }
	local PlayerCasts = self._PlayerToCasts[Player]
	if not PlayerCasts then
		return {}
	end
	local Result = {}
	for CastId in PlayerCasts do
		Result[#Result + 1] = CastId
	end
	return Result
end

-- Idempotent destroy.
function OwnershipRegistry.Destroy(self: any)
	if self._Destroyed then return end
	self._Destroyed = true
	table_clear(self._CastToPlayer)
	table_clear(self._PlayerToCasts)
	self._CastToPlayer  = nil
	self._PlayerToCasts = nil
	setmetatable(self, nil)
end

-- ─── Module Return ───────────────────────────────────────────────────────────

return table.freeze(setmetatable(OwnershipRegistry, {
	__index = function(_, Key)
		Logger:Warn(string_format("OwnershipRegistry: nil key '%s'", tostring(Key)))
	end,
	__newindex = function(_, Key, _Value)
		Logger:Error(string_format("OwnershipRegistry: write to protected key '%s'", tostring(Key)))
	end,
}))
